Name:		texlive-mintspirit
Version:	64461
Release:	2
Summary:	LaTeX support for MintSpirit font families
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/mintspirit
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/mintspirit.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/mintspirit.doc.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX
support for the MintSpirit and MintSpiritNo2 families of fonts,
designed by Hirwen Harendal. MintSpirit was originally designed
for use as a system font on a Linux Mint system. The No. 2
variant provides more conventional shapes for some glyphs.

%post
%{_sbindir}/texlive.post

%postun
if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_24uybq.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_2dxuba.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_3vy5j3.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_5cazkt.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_63vcua.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_6x4rw3.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_7ayy44.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_7u5374.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_amdskp.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_biiinc.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_bkoczj.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_dnk3mn.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_eex3ia.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_eqihrw.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_eqrkmo.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_fizmng.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_fm3wlu.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_j4bodc.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_k4fv75.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_l3e5vj.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_lm7mhw.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_lwraz3.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_me5dp6.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_oe76kg.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_ref42g.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_s7rd6p.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_taixll.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_tmtdfz.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt2_ywkmiw.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_2isll4.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_3sm7wd.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_3y5hmb.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_5lbatd.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_5yvi6n.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_675dmr.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_7enqs3.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_bjjcsi.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_f4utek.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_gcdgcc.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_gdx47l.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_girsvq.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_gr6qqq.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_imdxi4.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_lvhuc6.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_lzc2o4.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_oj7rfe.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_opresw.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_pulfbi.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_swumq4.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_v6lq4b.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_wk34ig.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_y4xqha.enc
%{_texmfdistdir}/fonts/enc/dvips/mintspirit/mntsprt_zt2pqo.enc
%{_texmfdistdir}/fonts/map/dvips/mintspirit/mintspirit.map
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpirit-Bold.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpirit-BoldItalic.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpirit-Italic.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpirit-Regular.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpiritNo2-Bold.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpiritNo2-BoldItalic.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpiritNo2-Italic.otf
%{_texmfdistdir}/fonts/opentype/arkandis/mintspirit/MintSpiritNo2-Regular.otf
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpirit-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-inf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-inf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-inf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-inf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-inf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpirit-Bold.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpirit-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpirit-Italic.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpirit-Regular.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpiritNo2-Bold.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpiritNo2-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpiritNo2-Italic.pfb
%{_texmfdistdir}/fonts/type1/arkandis/mintspirit/MintSpiritNo2-Regular.pfb
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-BoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpirit-Regular-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-BoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-inf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-inf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-lf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-sup-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/arkandis/mintspirit/MintSpiritNo2-Regular-tosf-ts1.vf
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpirit-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/LY1MintSpiritNoTwo-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpirit-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/OT1MintSpiritNoTwo-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpirit-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-Inf.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-Sup.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/T1MintSpiritNoTwo-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpirit-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpirit-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpirit-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpirit-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpiritNoTwo-LF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpiritNoTwo-OsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpiritNoTwo-TLF.fd
%{_texmfdistdir}/tex/latex/mintspirit/TS1MintSpiritNoTwo-TOsF.fd
%{_texmfdistdir}/tex/latex/mintspirit/mintspirit.sty
%{_texmfdistdir}/tex/latex/mintspirit/mintspirit2.sty
%doc %{_texmfdistdir}/doc/fonts/mintspirit/MintSpirit-Cat.pdf
%doc %{_texmfdistdir}/doc/fonts/mintspirit/OFL.txt
%doc %{_texmfdistdir}/doc/fonts/mintspirit/README
%doc %{_texmfdistdir}/doc/fonts/mintspirit/mintspirit-samples.pdf
%doc %{_texmfdistdir}/doc/fonts/mintspirit/mintspirit-samples.tex
%doc %{_texmfdistdir}/doc/fonts/mintspirit/mintspirit2-samples.pdf
%doc %{_texmfdistdir}/doc/fonts/mintspirit/mintspirit2-samples.tex

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
